language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra
    - sys-img-armeabi-v7a-android-21
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - oraclejdk8

env:
  global:
    # Add this
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=10

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &


# Add this
sudo: required


script:
  - android list target
  - ./gradlew connectedAndroidTest
  - ./gradlew build


after_success: ./scripts/travis_upload_release_to_github.py